# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: django-celery-beat
  version: 2.9.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 92404650f52fcb44cf08e2b09635cb1558327c54b1a5d570f0e2d3a22130934c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }},<4.0
    - celery >=5.2.3,<6.0
    - importlib-metadata
    - django-timezone-field >=5.0
    - tzdata
    - python-crontab >=2.3.4
    - cron-descriptor >=1.2.32,<2.0.0
    - django >=2.2,<6.1
    - pytest
    - kombu
tests:
  - python:
      imports:
        - django_celery_beat
        - django_celery_beat.migrations
      python_version: ${{ python_min }}.*
      pip_check: true

about:
  summary: Database-backed Periodic Tasks.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/celery/django-celery-beat

extra:
  recipe-maintainers:
    - rxm7706
